-- 004-migrate-sdb-proposals.sql
-- Migrate 32 SDB proposals from roadmap2 → Postgres agenthive
-- Generated: 2026-04-04
-- Uses OVERRIDING SYSTEM VALUE to preserve original IDs for traceability

BEGIN;

INSERT INTO proposal (display_id, title, proposal_type, category, domain_id, parent_id, status, rfc_state, priority, maturity_level, budget_limit_usd, tags) VALUES ('P001', 'CHILD-RFCS-CREATED', 'CAPABILITY', 'FEATURE', 'ENGINE', NULL, 'DRAFT', 'DRAFT', 5, 0, 0.0, NULL);
INSERT INTO proposal (display_id, title, proposal_type, category, domain_id, parent_id, status, rfc_state, priority, maturity_level, budget_limit_usd, tags) VALUES ('P002', 'proposal-001 - Test-Team-Memory-Sprint', 'DIRECTIVE', 'FEATURE', 'ENGINE', NULL, 'DRAFT', 'DRAFT', 5, 0, 0.0, NULL);
INSERT INTO proposal (display_id, title, proposal_type, category, domain_id, parent_id, status, rfc_state, priority, maturity_level, budget_limit_usd, tags) VALUES ('P003', 'Fix-hardcoded-SDB-database-names', 'DIRECTIVE', 'FEATURE', 'ENGINE', NULL, 'DRAFT', 'DRAFT', 5, 0, 0.0, '["sdb", "infrastructure"]'::jsonb);
INSERT INTO proposal (display_id, title, proposal_type, category, domain_id, parent_id, status, rfc_state, priority, maturity_level, budget_limit_usd, tags) VALUES ('P004', 'Fix-hardcoded-SDB-database-names', 'DIRECTIVE', 'FEATURE', 'ENGINE', NULL, 'DRAFT', 'DRAFT', 5, 0, 0.0, '["sdb", "infrastructure"]'::jsonb);
INSERT INTO proposal (display_id, title, proposal_type, category, domain_id, parent_id, status, rfc_state, priority, maturity_level, budget_limit_usd, tags) VALUES ('P005', 'proposal-004 - Agent-Profile-Upgrade-—-GitHub-Sync-Personality-Injection', 'DIRECTIVE', 'FEATURE', 'ENGINE', NULL, 'DRAFT', 'DRAFT', 5, 0, 0.0, NULL);
INSERT INTO proposal (display_id, title, proposal_type, category, domain_id, parent_id, status, rfc_state, priority, maturity_level, budget_limit_usd, tags) VALUES ('P006', 'proposal-005 - Messaging-Synchronization', 'DIRECTIVE', 'FEATURE', 'ENGINE', NULL, 'DRAFT', 'DRAFT', 5, 0, 0.0, NULL);
INSERT INTO proposal (display_id, title, proposal_type, category, domain_id, parent_id, status, rfc_state, priority, maturity_level, budget_limit_usd, tags) VALUES ('P007', 'RFC-20260401-BUSINESS-DESIGN', 'RFC', 'FEATURE', 'ENGINE', NULL, 'DRAFT', 'DRAFT', 5, 0, 0.0, NULL);
INSERT INTO proposal (display_id, title, proposal_type, category, domain_id, parent_id, status, rfc_state, priority, maturity_level, budget_limit_usd, tags) VALUES ('P008', 'RFC-20260401-BUSINESS-STRATEGY', 'RFC', 'FEATURE', 'ENGINE', NULL, 'DRAFT', 'DRAFT', 5, 0, 0.0, NULL);
INSERT INTO proposal (display_id, title, proposal_type, category, domain_id, parent_id, status, rfc_state, priority, maturity_level, budget_limit_usd, tags) VALUES ('P009', 'RFC-20260401-CONFIG-REDESIGN', 'RFC', 'FEATURE', 'ENGINE', NULL, 'DRAFT', 'DRAFT', 5, 0, 0.0, NULL);
INSERT INTO proposal (display_id, title, proposal_type, category, domain_id, parent_id, status, rfc_state, priority, maturity_level, budget_limit_usd, tags) VALUES ('P010', 'RFC-20260401-DATA-MODEL', 'RFC', 'FEATURE', 'ENGINE', NULL, 'DRAFT', 'DRAFT', 5, 0, 0.0, NULL);
INSERT INTO proposal (display_id, title, proposal_type, category, domain_id, parent_id, status, rfc_state, priority, maturity_level, budget_limit_usd, tags) VALUES ('P011', 'RFC-20260401-MCP-TOOL-SPEC', 'RFC', 'FEATURE', 'ENGINE', NULL, 'DRAFT', 'DRAFT', 5, 0, 0.0, NULL);
INSERT INTO proposal (display_id, title, proposal_type, category, domain_id, parent_id, status, rfc_state, priority, maturity_level, budget_limit_usd, tags) VALUES ('P012', 'RFC-20260401-MESSAGES-PULSE', 'RFC', 'FEATURE', 'ENGINE', NULL, 'DRAFT', 'DRAFT', 5, 0, 0.0, NULL);
INSERT INTO proposal (display_id, title, proposal_type, category, domain_id, parent_id, status, rfc_state, priority, maturity_level, budget_limit_usd, tags) VALUES ('P013', 'RFC-20260401-MESSAGING', 'RFC', 'FEATURE', 'ENGINE', NULL, 'COMPLETE', 'COMPLETE', 5, 2, 0.0, NULL);
INSERT INTO proposal (display_id, title, proposal_type, category, domain_id, parent_id, status, rfc_state, priority, maturity_level, budget_limit_usd, tags) VALUES ('P014', 'RFC-20260401-MOBILE-ALERT', 'RFC', 'FEATURE', 'ENGINE', NULL, 'DRAFT', 'DRAFT', 5, 0, 0.0, NULL);
INSERT INTO proposal (display_id, title, proposal_type, category, domain_id, parent_id, status, rfc_state, priority, maturity_level, budget_limit_usd, tags) VALUES ('P015', 'RFC-20260401-MOBILE-VISIONARY', 'RFC', 'FEATURE', 'ENGINE', NULL, 'DRAFT', 'DRAFT', 5, 0, 0.0, NULL);
INSERT INTO proposal (display_id, title, proposal_type, category, domain_id, parent_id, status, rfc_state, priority, maturity_level, budget_limit_usd, tags) VALUES ('P016', 'RFC-20260401-PIPELINE-PREFLIGHT', 'RFC', 'FEATURE', 'ENGINE', NULL, 'DRAFT', 'DRAFT', 5, 0, 0.0, NULL);
INSERT INTO proposal (display_id, title, proposal_type, category, domain_id, parent_id, status, rfc_state, priority, maturity_level, budget_limit_usd, tags) VALUES ('P017', 'RFC-20260401-PIPELINE-VERIFICATION', 'RFC', 'FEATURE', 'ENGINE', NULL, 'DRAFT', 'DRAFT', 5, 0, 0.0, NULL);
INSERT INTO proposal (display_id, title, proposal_type, category, domain_id, parent_id, status, rfc_state, priority, maturity_level, budget_limit_usd, tags) VALUES ('P018', 'RFC-20260401-PRODUCT-STATEMACHINE', 'RFC', 'FEATURE', 'ENGINE', NULL, 'DRAFT', 'DRAFT', 5, 0, 0.0, NULL);
INSERT INTO proposal (display_id, title, proposal_type, category, domain_id, parent_id, status, rfc_state, priority, maturity_level, budget_limit_usd, tags) VALUES ('P019', 'RFC-20260401-PRODUCT-TEMPLATE', 'RFC', 'FEATURE', 'ENGINE', NULL, 'DRAFT', 'DRAFT', 5, 0, 0.0, NULL);
INSERT INTO proposal (display_id, title, proposal_type, category, domain_id, parent_id, status, rfc_state, priority, maturity_level, budget_limit_usd, tags) VALUES ('P020', 'RFC-20260401-SECURITY-CHILD-051', 'RFC', 'FEATURE', 'ENGINE', NULL, 'DRAFT', 'DRAFT', 5, 0, 0.0, NULL);
INSERT INTO proposal (display_id, title, proposal_type, category, domain_id, parent_id, status, rfc_state, priority, maturity_level, budget_limit_usd, tags) VALUES ('P021', 'RFC-20260401-SECURITY-CHILD-052', 'RFC', 'FEATURE', 'ENGINE', NULL, 'DRAFT', 'DRAFT', 5, 0, 0.0, NULL);
INSERT INTO proposal (display_id, title, proposal_type, category, domain_id, parent_id, status, rfc_state, priority, maturity_level, budget_limit_usd, tags) VALUES ('P022', 'RFC-20260401-SECURITY-CHILD-054', 'RFC', 'FEATURE', 'ENGINE', NULL, 'DRAFT', 'DRAFT', 5, 0, 0.0, NULL);
INSERT INTO proposal (display_id, title, proposal_type, category, domain_id, parent_id, status, rfc_state, priority, maturity_level, budget_limit_usd, tags) VALUES ('P023', 'RFC-20260401-SECURITY-CHILD-056', 'RFC', 'FEATURE', 'ENGINE', NULL, 'DRAFT', 'DRAFT', 5, 0, 0.0, NULL);
INSERT INTO proposal (display_id, title, proposal_type, category, domain_id, parent_id, status, rfc_state, priority, maturity_level, budget_limit_usd, tags) VALUES ('P024', 'RFC-20260401-SECURITY', 'RFC', 'FEATURE', 'ENGINE', NULL, 'DRAFT', 'DRAFT', 5, 0, 0.0, NULL);
INSERT INTO proposal (display_id, title, proposal_type, category, domain_id, parent_id, status, rfc_state, priority, maturity_level, budget_limit_usd, tags) VALUES ('P025', 'RFC-20260401-SPENDING-VISIBILITY', 'RFC', 'FEATURE', 'ENGINE', NULL, 'DRAFT', 'DRAFT', 5, 0, 0.0, NULL);
INSERT INTO proposal (display_id, title, proposal_type, category, domain_id, parent_id, status, rfc_state, priority, maturity_level, budget_limit_usd, tags) VALUES ('P026', 'RFC-20260401-TUI-COCKPIT', 'RFC', 'FEATURE', 'ENGINE', NULL, 'DRAFT', 'DRAFT', 5, 0, 0.0, NULL);
INSERT INTO proposal (display_id, title, proposal_type, category, domain_id, parent_id, status, rfc_state, priority, maturity_level, budget_limit_usd, tags) VALUES ('P027', 'RFC-20260401-WORKFORCE-CORE', 'RFC', 'FEATURE', 'ENGINE', NULL, 'DRAFT', 'DRAFT', 5, 0, 0.0, NULL);
INSERT INTO proposal (display_id, title, proposal_type, category, domain_id, parent_id, status, rfc_state, priority, maturity_level, budget_limit_usd, tags) VALUES ('P028', 'Agent Memory Architecture: 4-Layer Memory System', 'RFC', 'Infrastructure', 'AGENT-MEMORY', NULL, 'DRAFT', 'DRAFT', 2, 0, 500.0, NULL);
INSERT INTO proposal (display_id, title, proposal_type, category, domain_id, parent_id, status, rfc_state, priority, maturity_level, budget_limit_usd, tags) VALUES ('P029', 'Eliminate WebSocket Bridge - Use SDB Native Subscriptions Directly', 'RFC', 'INFRA', 'ENGINE', NULL, 'DRAFT', 'DRAFT', 5, 0, 0.0, NULL);
INSERT INTO proposal (display_id, title, proposal_type, category, domain_id, parent_id, status, rfc_state, priority, maturity_level, budget_limit_usd, tags) VALUES ('P030', 'Agent Memory Architecture: 4-Layer Memory System', 'RFC', 'Infrastructure', 'AGENT-MEMORY', NULL, 'DRAFT', 'DRAFT', 2, 0, 500.0, NULL);
INSERT INTO proposal (display_id, title, proposal_type, category, domain_id, parent_id, status, rfc_state, priority, maturity_level, budget_limit_usd, tags) VALUES ('P031', 'Agent Memory Architecture: 4-Layer Memory System', 'RFC', 'Infrastructure', 'AGENT-MEMORY', NULL, 'DRAFT', 'DRAFT', 2, 0, 500.0, NULL);
INSERT INTO proposal (display_id, title, proposal_type, category, domain_id, parent_id, status, rfc_state, priority, maturity_level, budget_limit_usd, tags) VALUES ('P032', 'Code Review: Security & Quality Issues Found', 'RFC', 'SECURITY', 'ENGINE', NULL, 'REVIEW', 'REVIEW', 2, 1, 0.0, NULL);

COMMIT;