-- P674: Notification router — kind+payload contract decoupled from transport.
--
-- Adds:
--   - roadmap.notification_queue.kind (event identifier; routing key)
--   - roadmap.notification_queue.dispatch_attempts (retry accounting)
--   - roadmap.notification_queue.last_error (last transport failure detail)
--   - roadmap.notification_route (operator-owned policy: kind+severity → transport)
--   - pg_notify trigger so the router service wakes on enqueue
--
-- Preserves existing columns (channel, status, delivered_at, metadata). Existing
-- callers continue to work; the router treats rows with non-null `channel` as
-- legacy direct-route during the deprecation window.
--
-- Severity vocabulary stays as the existing CHECK constraint:
--   INFO | ALERT | URGENT | CRITICAL.

BEGIN;

-- 1. Extend notification_queue with routing-contract columns.
ALTER TABLE roadmap.notification_queue
	ADD COLUMN IF NOT EXISTS kind text,
	ADD COLUMN IF NOT EXISTS dispatch_attempts integer NOT NULL DEFAULT 0,
	ADD COLUMN IF NOT EXISTS last_error text;

-- Make legacy `channel` column optional. New callers write `kind` instead.
-- The CHECK constraint stays so legacy direct-route values remain validated.
ALTER TABLE roadmap.notification_queue
	ALTER COLUMN channel DROP NOT NULL,
	ALTER COLUMN channel DROP DEFAULT;

ALTER TABLE roadmap.notification_queue
	DROP CONSTRAINT IF EXISTS notification_queue_channel_check;

ALTER TABLE roadmap.notification_queue
	ADD CONSTRAINT notification_queue_channel_check
	CHECK (channel IS NULL OR channel = ANY (ARRAY['discord', 'email', 'sms', 'push', 'digest']));

-- A row must identify itself either by `kind` (P674 contract) OR by `channel` (legacy).
ALTER TABLE roadmap.notification_queue
	DROP CONSTRAINT IF EXISTS notification_queue_kind_or_channel;

ALTER TABLE roadmap.notification_queue
	ADD CONSTRAINT notification_queue_kind_or_channel
	CHECK (kind IS NOT NULL OR channel IS NOT NULL);

COMMENT ON COLUMN roadmap.notification_queue.kind IS
	'Stable event identifier resolved against notification_route. Examples: spawn_no_ladder, schema_drift, schema_drift_repeated. NULL is allowed only for legacy rows that set `channel` directly.';
COMMENT ON COLUMN roadmap.notification_queue.dispatch_attempts IS
	'Retry counter; router increments on transport failure. AC-6 escalates after 5 attempts.';
COMMENT ON COLUMN roadmap.notification_queue.last_error IS
	'Most recent transport failure message; trimmed to 4000 chars by router.';

-- Index pending rows (ordered for FIFO drain).
DROP INDEX IF EXISTS roadmap.idx_notification_queue_pending;
CREATE INDEX idx_notification_queue_pending
	ON roadmap.notification_queue (severity, created_at)
	WHERE status = 'pending';

-- 2. notification_route: operator-owned routing policy.
CREATE TABLE IF NOT EXISTS roadmap.notification_route (
	id           bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	kind         text NOT NULL,
	severity_min text NOT NULL DEFAULT 'INFO'
		CHECK (severity_min = ANY (ARRAY['INFO', 'ALERT', 'URGENT', 'CRITICAL'])),
	transport    text NOT NULL
		CHECK (transport = ANY (ARRAY[
			'discord_webhook', 'mcp_agent', 'in_app', 'log_only',
			'github_issue', 'email', 'sms'
		])),
	target       text,                       -- transport-specific (URL, agent identity, channel)
	template     text,                       -- optional payload template
	enabled      boolean NOT NULL DEFAULT true,
	priority     integer NOT NULL DEFAULT 100,
	notes        text,
	created_at   timestamptz NOT NULL DEFAULT now(),
	updated_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_notification_route_kind
	ON roadmap.notification_route (kind, enabled);

COMMENT ON TABLE roadmap.notification_route IS
	'P674 routing policy. Resolves (kind, severity) to one or more transports. Operator-owned: change with SQL UPDATE, no code change required.';

-- 3. pg_notify on enqueue — router wakes within 1s.
CREATE OR REPLACE FUNCTION roadmap.notify_notification_enqueued()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
	PERFORM pg_notify(
		'notification_enqueued',
		json_build_object(
			'id', NEW.id,
			'kind', NEW.kind,
			'severity', NEW.severity,
			'proposal_id', NEW.proposal_id
		)::text
	);
	RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS notification_queue_enqueued ON roadmap.notification_queue;
CREATE TRIGGER notification_queue_enqueued
	AFTER INSERT ON roadmap.notification_queue
	FOR EACH ROW
	WHEN (NEW.status = 'pending')
	EXECUTE FUNCTION roadmap.notify_notification_enqueued();

-- 4. Seed default routes that preserve existing behavior.
--    Existing call site (agent-spawner.ts) will be migrated to use kind='spawn_no_ladder';
--    today the discord webhook target is read from env at runtime, so we leave `target` NULL
--    and the discord_webhook adapter resolves it from `DISCORD_WEBHOOK_URL` env.
INSERT INTO roadmap.notification_route (kind, severity_min, transport, target, notes)
VALUES
	('spawn_no_ladder',          'ALERT',    'discord_webhook', NULL, 'P674 seed: preserve existing agent-spawner escalation behavior'),
	('schema_drift',             'INFO',     'discord_webhook', NULL, 'P675 first-occurrence drift posts'),
	('schema_drift_repeated',    'CRITICAL', 'discord_webhook', NULL, 'P675 repeat-occurrence escalations'),
	('schema_drift_repeated',    'CRITICAL', 'log_only',        NULL, 'P675 backstop: never lose a critical event'),
	('notification_dispatch_failed', 'CRITICAL', 'log_only',    NULL, 'P674 self-healing: failed-dispatch escalations always log even if Discord is down')
ON CONFLICT DO NOTHING;

COMMIT;
