// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Ac = __t.object("Ac", {
  id: __t.u64(),
  acId: __t.string(),
  stepId: __t.string(),
  description: __t.string(),
  verified: __t.bool(),
});
export type Ac = __Infer<typeof Ac>;
