// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Adr = __t.object("Adr", {
  id: __t.u64(),
  stepId: __t.string(),
  teamId: __t.option(__t.string()),
  title: __t.string(),
  decision: __t.string(),
  rationale: __t.string(),
  createdAt: __t.u64(),
});
export type Adr = __Infer<typeof Adr>;
