// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AgentBudget = __t.object("AgentBudget", {
  agentId: __t.string(),
  totalSpent: __t.f64(),
  hardLimit: __t.f64(),
  isFrozen: __t.bool(),
});
export type AgentBudget = __Infer<typeof AgentBudget>;
