// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Art = __t.object("Art", {
  id: __t.u64(),
  stateId: __t.string(),
  artType: __t.string(),
  uri: __t.string(),
  hash: __t.string(),
  agentId: __t.option(__t.string()),
  createdAt: __t.u64(),
});
export type Art = __Infer<typeof Art>;
