// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  proposalId: __t.u64().name("proposal_id"),
  displayId: __t.string().name("display_id"),
  fileName: __t.string().name("file_name"),
  relativePath: __t.string().name("relative_path"),
  fileType: __t.string().name("file_type"),
  contentHash: __t.string().name("content_hash"),
  visionSummary: __t.option(__t.string()).name("vision_summary"),
  timestamp: __t.u64(),
});
