// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Cfg = __t.object("Cfg", {
  id: __t.u64(),
  agentId: __t.string(),
  section: __t.string(),
  content: __t.string(),
  updatedAt: __t.u64(),
});
export type Cfg = __Infer<typeof Cfg>;
