// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Comp = __t.object("Comp", {
  id: __t.u64(),
  claimId: __t.string(),
  stepId: __t.string(),
  agentId: __t.string(),
  claimedAt: __t.u64(),
  expiresAt: __t.u64(),
  active: __t.bool(),
});
export type Comp = __Infer<typeof Comp>;
