// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  displayId: __t.string(),
  proposalType: __t.string(),
  category: __t.string(),
  domainId: __t.string(),
  title: __t.string(),
  priority: __t.string(),
  bodyMarkdown: __t.option(__t.string()),
  parentId: __t.option(__t.u64()),
  budgetLimitUsd: __t.f64(),
};
