// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const CreateProposalReducer = __t.object("CreateProposalReducer", {
  title: __t.string(),
  description: __t.string(),
  proposedBy: __t.string(),
});
export type CreateProposalReducer = __Infer<typeof CreateProposalReducer>;
