// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const DeleteStateNoteReducer = __t.object("DeleteStateNoteReducer", {
  noteId: __t.u64(),
  agentId: __t.string(),
});
export type DeleteStateNoteReducer = __Infer<typeof DeleteStateNoteReducer>;
