// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Event = __t.object("Event", {
  id: __t.u64(),
  eventId: __t.string(),
  actor: __t.string(),
  action: __t.string(),
  stateId: __t.option(__t.string()),
  payload: __t.string(),
  timestamp: __t.u64(),
});
export type Event = __Infer<typeof Event>;
