// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Flow = __t.object("Flow", {
  id: __t.u64(),
  flowId: __t.string(),
  stepId: __t.string(),
  fromStatus: __t.string(),
  toStatus: __t.string(),
  reason: __t.string(),
  changedBy: __t.string(),
  timestamp: __t.u64(),
});
export type Flow = __Infer<typeof Flow>;
