// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const GrantPrivilegeReducer = __t.object("GrantPrivilegeReducer", {
  agentId: __t.string(),
  permission: __t.string(),
  grantedBy: __t.string(),
});
export type GrantPrivilegeReducer = __Infer<typeof GrantPrivilegeReducer>;
