// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// Generated from live SpacetimeDB schema on 2026-04-01T01:18:42.248Z

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import { AddTeamMemberReducer } from "./add_team_member_reducer.ts";
import { CacheClearReducer } from "./cache_clear_reducer.ts";
import { CacheSetReducer } from "./cache_set_reducer.ts";
import { ClaimStepReducer } from "./claim_step_reducer.ts";
import { CreateAcReducer } from "./create_ac_reducer.ts";
import { CreateChannelReducer } from "./create_channel_reducer.ts";
import { CreateCompReducer } from "./create_comp_reducer.ts";
import { CreateDiscussionReducer } from "./create_discussion_reducer.ts";
import { CreateGoalReducer } from "./create_goal_reducer.ts";
import { CreateProposalReducer } from "./create_proposal_reducer.ts";
import { CreateStateNoteReducer } from "./create_state_note_reducer.ts";
import { CreateStepReducer } from "./create_step_reducer.ts";
import { CreateTeamReducer } from "./create_team_reducer.ts";
import { DeleteDiscussionReducer } from "./delete_discussion_reducer.ts";
import { DeleteStateNoteReducer } from "./delete_state_note_reducer.ts";
import { DeleteStepReducer } from "./delete_step_reducer.ts";
import { EmitEventReducer } from "./emit_event_reducer.ts";
import { GrantPrivilegeReducer } from "./grant_privilege_reducer.ts";
import { MarkReadReducer } from "./mark_read_reducer.ts";
import { ProvisionSandboxReducer } from "./provision_sandbox_reducer.ts";
import { RecordTokensReducer } from "./record_tokens_reducer.ts";
import { RegisterAgentReducer } from "./register_agent_reducer.ts";
import { ReleaseClaimReducer } from "./release_claim_reducer.ts";
import { RemoveTeamMemberReducer } from "./remove_team_member_reducer.ts";
import { RestoreStepReducer } from "./restore_step_reducer.ts";
import { SendMessageReducer } from "./send_message_reducer.ts";
import { SetConfigReducer } from "./set_config_reducer.ts";
import { SubmitReviewReducer } from "./submit_review_reducer.ts";
import { SubscribeChannelReducer } from "./subscribe_channel_reducer.ts";
import { TransitionStepReducer } from "./transition_step_reducer.ts";
import { UpdateGoalStatusReducer } from "./update_goal_status_reducer.ts";
import { VerifyAcReducer } from "./verify_ac_reducer.ts";

// Import all procedure arg schemas

// Import all table schema definitions
import { Ac } from "./ac_table.ts";
import { Adr } from "./adr_table.ts";
import { Agent } from "./agent_table.ts";
import { AgentBudget } from "./agent_budget_table.ts";
import { AgentSkill } from "./agent_skill_table.ts";
import { Art } from "./art_table.ts";
import { Cfg } from "./cache_table.ts";
import { Chan } from "./cfg_table.ts";
import { Claim } from "./chan_table.ts";
import { Comp } from "./claim_table.ts";
import { ContextCache } from "./comp_table.ts";
import { Discussion } from "./discussion_table.ts";
import { Event } from "./event_table.ts";
import { Flow } from "./flow_table.ts";
import { Goal } from "./goal_table.ts";
import { Mem } from "./mem_table.ts";
import { Member } from "./member_table.ts";
import { Msg } from "./msg_table.ts";
import { Note } from "./note_table.ts";
import { Privilege } from "./privilege_table.ts";
import { Prop } from "./prop_table.ts";
import { Res } from "./res_table.ts";
import { Rev } from "./rev_table.ts";
import { Sbx } from "./sbx_table.ts";
import { Skill } from "./skill_table.ts";
import { StateNote } from "./state_note_table.ts";
import { Step } from "./step_table.ts";
import { Sub } from "./sub_table.ts";
import { Team } from "./team_table.ts";
import { Test } from "./test_table.ts";
import { TokenLedger } from "./token_ledger_table.ts";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. */
const tablesSchema = __schema({
  ac: __table({
    name: 'ac',
    indexes: [
      { accessor: 'id', name: 'ac_id_idx_btree', algorithm: 'btree', columns: [
        'id'] }],
    constraints: [],
  }, Ac),
  adr: __table({
    name: 'adr',
    indexes: [
      { accessor: 'id', name: 'adr_id_idx_btree', algorithm: 'btree', columns: [
        'id'] }],
    constraints: [],
  }, Adr),
  agent: __table({
    name: 'agent',
    indexes: [
      { accessor: 'id', name: 'agent_id_idx_btree', algorithm: 'btree', columns: [
        'id'] }],
    constraints: [],
  }, Agent),
  agent_budget: __table({
    name: 'agent_budget',
    indexes: [
      { accessor: 'agentId', name: 'agent_budget_agent_id_idx_btree', algorithm: 'btree', columns: [
        'agentId'] }],
    constraints: [],
  }, AgentBudget),
  agent_skill: __table({
    name: 'agent_skill',
    indexes: [
      { accessor: 'id', name: 'agent_skill_id_idx_btree', algorithm: 'btree', columns: [
        'id'] }],
    constraints: [],
  }, AgentSkill),
  art: __table({
    name: 'art',
    indexes: [
      { accessor: 'id', name: 'art_id_idx_btree', algorithm: 'btree', columns: [
        'id'] }],
    constraints: [],
  }, Art),
  cache: __table({
    name: 'cache',
    indexes: [
      { accessor: 'id', name: 'cache_id_idx_btree', algorithm: 'btree', columns: [
        'id'] }],
    constraints: [],
  }, Cfg),
  cfg: __table({
    name: 'cfg',
    indexes: [
      { accessor: 'key', name: 'cfg_key_idx_btree', algorithm: 'btree', columns: [
        'key'] }],
    constraints: [],
  }, Chan),
  chan: __table({
    name: 'chan',
    indexes: [
      { accessor: 'id', name: 'chan_id_idx_btree', algorithm: 'btree', columns: [
        'id'] }],
    constraints: [],
  }, Claim),
  claim: __table({
    name: 'claim',
    indexes: [
      { accessor: 'id', name: 'claim_id_idx_btree', algorithm: 'btree', columns: [
        'id'] }],
    constraints: [],
  }, Comp),
  comp: __table({
    name: 'comp',
    indexes: [
      { accessor: 'id', name: 'comp_id_idx_btree', algorithm: 'btree', columns: [
        'id'] }],
    constraints: [],
  }, ContextCache),
  discussion: __table({
    name: 'discussion',
    indexes: [
      { accessor: 'id', name: 'discussion_id_idx_btree', algorithm: 'btree', columns: [
        'id'] }],
    constraints: [],
  }, Discussion),
  event: __table({
    name: 'event',
    indexes: [
      { accessor: 'id', name: 'event_id_idx_btree', algorithm: 'btree', columns: [
        'id'] }],
    constraints: [],
  }, Event),
  flow: __table({
    name: 'flow',
    indexes: [
      { accessor: 'id', name: 'flow_id_idx_btree', algorithm: 'btree', columns: [
        'id'] }],
    constraints: [],
  }, Flow),
  goal: __table({
    name: 'goal',
    indexes: [
      { accessor: 'id', name: 'goal_id_idx_btree', algorithm: 'btree', columns: [
        'id'] }],
    constraints: [],
  }, Goal),
  mem: __table({
    name: 'mem',
    indexes: [
      { accessor: 'id', name: 'mem_id_idx_btree', algorithm: 'btree', columns: [
        'id'] }],
    constraints: [],
  }, Mem),
  member: __table({
    name: 'member',
    indexes: [
      { accessor: 'id', name: 'member_id_idx_btree', algorithm: 'btree', columns: [
        'id'] }],
    constraints: [],
  }, Member),
  msg: __table({
    name: 'msg',
    indexes: [
      { accessor: 'id', name: 'msg_id_idx_btree', algorithm: 'btree', columns: [
        'id'] }],
    constraints: [],
  }, Msg),
  note: __table({
    name: 'note',
    indexes: [
      { accessor: 'id', name: 'note_id_idx_btree', algorithm: 'btree', columns: [
        'id'] }],
    constraints: [],
  }, Note),
  privilege: __table({
    name: 'privilege',
    indexes: [
      { accessor: 'id', name: 'privilege_id_idx_btree', algorithm: 'btree', columns: [
        'id'] }],
    constraints: [],
  }, Privilege),
  prop: __table({
    name: 'prop',
    indexes: [
      { accessor: 'id', name: 'prop_id_idx_btree', algorithm: 'btree', columns: [
        'id'] }],
    constraints: [],
  }, Prop),
  res: __table({
    name: 'res',
    indexes: [
      { accessor: 'id', name: 'res_id_idx_btree', algorithm: 'btree', columns: [
        'id'] }],
    constraints: [],
  }, Res),
  rev: __table({
    name: 'rev',
    indexes: [
      { accessor: 'id', name: 'rev_id_idx_btree', algorithm: 'btree', columns: [
        'id'] }],
    constraints: [],
  }, Rev),
  sbx: __table({
    name: 'sbx',
    indexes: [
      { accessor: 'containerId', name: 'sbx_container_id_idx_btree', algorithm: 'btree', columns: [
        'containerId'] }],
    constraints: [],
  }, Sbx),
  skill: __table({
    name: 'skill',
    indexes: [
      { accessor: 'id', name: 'skill_id_idx_btree', algorithm: 'btree', columns: [
        'id'] }],
    constraints: [],
  }, Skill),
  state_note: __table({
    name: 'state_note',
    indexes: [
      { accessor: 'id', name: 'state_note_id_idx_btree', algorithm: 'btree', columns: [
        'id'] }],
    constraints: [],
  }, StateNote),
  step: __table({
    name: 'step',
    indexes: [
      { accessor: 'id', name: 'step_id_idx_btree', algorithm: 'btree', columns: [
        'id'] }],
    constraints: [],
  }, Step),
  sub: __table({
    name: 'sub',
    indexes: [
      { accessor: 'id', name: 'sub_id_idx_btree', algorithm: 'btree', columns: [
        'id'] }],
    constraints: [],
  }, Sub),
  team: __table({
    name: 'team',
    indexes: [
      { accessor: 'id', name: 'team_id_idx_btree', algorithm: 'btree', columns: [
        'id'] }],
    constraints: [],
  }, Team),
  test: __table({
    name: 'test',
    indexes: [
      { accessor: 'id', name: 'test_id_idx_btree', algorithm: 'btree', columns: [
        'id'] }],
    constraints: [],
  }, Test),
  token_ledger: __table({
    name: 'token_ledger',
    indexes: [
      { accessor: 'id', name: 'token_ledger_id_idx_btree', algorithm: 'btree', columns: [
        'id'] }],
    constraints: [],
  }, TokenLedger),
});

/** The schema information for all reducers in this module. */
const reducersSchema = __reducers(
  __reducerSchema("add_team_member", AddTeamMemberReducer),
  __reducerSchema("cache_clear", CacheClearReducer),
  __reducerSchema("cache_set", CacheSetReducer),
  __reducerSchema("claim_step", ClaimStepReducer),
  __reducerSchema("create_ac", CreateAcReducer),
  __reducerSchema("create_channel", CreateChannelReducer),
  __reducerSchema("create_comp", CreateCompReducer),
  __reducerSchema("create_discussion", CreateDiscussionReducer),
  __reducerSchema("create_goal", CreateGoalReducer),
  __reducerSchema("create_proposal", CreateProposalReducer),
  __reducerSchema("create_state_note", CreateStateNoteReducer),
  __reducerSchema("create_step", CreateStepReducer),
  __reducerSchema("create_team", CreateTeamReducer),
  __reducerSchema("delete_discussion", DeleteDiscussionReducer),
  __reducerSchema("delete_state_note", DeleteStateNoteReducer),
  __reducerSchema("delete_step", DeleteStepReducer),
  __reducerSchema("emit_event", EmitEventReducer),
  __reducerSchema("grant_privilege", GrantPrivilegeReducer),
  __reducerSchema("mark_read", MarkReadReducer),
  __reducerSchema("provision_sandbox", ProvisionSandboxReducer),
  __reducerSchema("record_tokens", RecordTokensReducer),
  __reducerSchema("register_agent", RegisterAgentReducer),
  __reducerSchema("release_claim", ReleaseClaimReducer),
  __reducerSchema("remove_team_member", RemoveTeamMemberReducer),
  __reducerSchema("restore_step", RestoreStepReducer),
  __reducerSchema("send_message", SendMessageReducer),
  __reducerSchema("set_config", SetConfigReducer),
  __reducerSchema("submit_review", SubmitReviewReducer),
  __reducerSchema("subscribe_channel", SubscribeChannelReducer),
  __reducerSchema("transition_step", TransitionStepReducer),
  __reducerSchema("update_goal_status", UpdateGoalStatusReducer),
  __reducerSchema("verify_ac", VerifyAcReducer),
);

/** The schema information for all procedures in this module. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.1.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}
