// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Mem = __t.object("Mem", {
  id: __t.u64(),
  agentId: __t.string(),
  scope: __t.string(),
  stateId: __t.option(__t.string()),
  key: __t.string(),
  val: __t.string(),
  updated: __t.u64(),
});
export type Mem = __Infer<typeof Mem>;
