// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Member = __t.object("Member", {
  id: __t.u64(),
  teamId: __t.string(),
  agentId: __t.string(),
  role: __t.string(),
  joinedAt: __t.u64(),
});
export type Member = __Infer<typeof Member>;
