// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Msg = __t.object("Msg", {
  id: __t.u64(),
  channelName: __t.string(),
  sender: __t.string(),
  content: __t.string(),
  timestamp: __t.u64(),
  msgType: __t.string(),
});
export type Msg = __Infer<typeof Msg>;
