// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Note = __t.object("Note", {
  id: __t.u64(),
  noteId: __t.string(),
  agentId: __t.string(),
  msgId: __t.u64(),
  noteType: __t.string(),
  read: __t.bool(),
  timestamp: __t.u64(),
});
export type Note = __Infer<typeof Note>;
