// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  displayId: __t.string().name("display_id"),
  parentId: __t.option(__t.u64()).name("parent_id"),
  proposalType: __t.string().name("proposal_type"),
  category: __t.string(),
  domainId: __t.string().name("domain_id"),
  title: __t.string(),
  status: __t.string(),
  priority: __t.string(),
  bodyMarkdown: __t.option(__t.string()).name("body_markdown"),
  processLogic: __t.option(__t.string()).name("process_logic"),
  maturityLevel: __t.option(__t.u32()).name("maturity_level"),
  repositoryPath: __t.option(__t.string()).name("repository_path"),
  budgetLimitUsd: __t.f64().name("budget_limit_usd"),
  tags: __t.option(__t.string()),
  createdAt: __t.u64().name("created_at"),
  updatedAt: __t.u64().name("updated_at"),
});
