// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Prop = __t.object("Prop", {
  id: __t.u64(),
  title: __t.string(),
  description: __t.string(),
  proposedBy: __t.string(),
  status: __t.string(),
  stateId: __t.option(__t.string()),
  createdAt: __t.u64(),
});
export type Prop = __Infer<typeof Prop>;
