// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  proposalId: __t.u64().name("proposal_id"),
  authorIdentity: __t.string().name("author_identity"),
  versionNumber: __t.u32().name("version_number"),
  changeSummary: __t.string().name("change_summary"),
  bodyDelta: __t.option(__t.string()).name("body_delta"),
  metadataDeltaJson: __t.string().name("metadata_delta_json"),
  gitCommitSha: __t.option(__t.string()).name("git_commit_sha"),
  timestamp: __t.u64(),
});
