// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const RecordTokensReducer = __t.object("RecordTokensReducer", {
  callId: __t.string(),
  agentId: __t.string(),
  modelName: __t.string(),
  inputTokens: __t.u64(),
  outputTokens: __t.u64(),
  cachedTokens: __t.u64(),
  totalUsd: __t.f64(),
});
export type RecordTokensReducer = __Infer<typeof RecordTokensReducer>;
