// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const RegisterAgentReducer = __t.object("RegisterAgentReducer", {
  id: __t.string(),
  agentType: __t.string(),
  name: __t.string(),
  reportsTo: __t.option(__t.string()),
});
export type RegisterAgentReducer = __Infer<typeof RegisterAgentReducer>;
