// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Res = __t.object("Res", {
  id: __t.u64(),
  resId: __t.string(),
  testId: __t.string(),
  passed: __t.bool(),
  duration: __t.f64(),
  error: __t.string(),
  timestamp: __t.u64(),
});
export type Res = __Infer<typeof Res>;
