// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const RestoreStepReducer = __t.object("RestoreStepReducer", {
  displayId: __t.string(),
  parentId: __t.option(__t.u64()),
  depth: __t.u64(),
  compId: __t.option(__t.string()),
  teamId: __t.option(__t.string()),
  goalId: __t.option(__t.string()),
  title: __t.string(),
  status: __t.string(),
  body: __t.string(),
  description: __t.string(),
  acceptanceCriteria: __t.string(),
  implementationNotes: __t.string(),
  finalSummary: __t.string(),
  priority: __t.string(),
  labels: __t.string(),
  dependencies: __t.string(),
  assignee: __t.string(),
  claimedBy: __t.option(__t.string()),
  claimedAt: __t.option(__t.u64()),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type RestoreStepReducer = __Infer<typeof RestoreStepReducer>;
