// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Rev = __t.object("Rev", {
  id: __t.u64(),
  stepId: __t.string(),
  reviewerId: __t.string(),
  verdict: __t.string(),
  rationale: __t.string(),
  timestamp: __t.u64(),
});
export type Rev = __Infer<typeof Rev>;
