// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Sbx = __t.object("Sbx", {
  containerId: __t.string(),
  agentId: __t.string(),
  token: __t.string(),
  status: __t.string(),
  createdAt: __t.u64(),
  expiresAt: __t.u64(),
});
export type Sbx = __Infer<typeof Sbx>;
