// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  agentIdentity: __t.string().primaryKey().name("agent_identity"),
  dailyLimitUsd: __t.f64().name("daily_limit_usd"),
  totalSpentTodayUsd: __t.f64().name("total_spent_today_usd"),
  isFrozen: __t.bool().name("is_frozen"),
});
