// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const StateNote = __t.object("StateNote", {
  id: __t.u64(),
  stepId: __t.string(),
  agentId: __t.string(),
  content: __t.string(),
  noteType: __t.string(),
  createdAt: __t.u64(),
});
export type StateNote = __Infer<typeof StateNote>;
