// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Sub = __t.object("Sub", {
  id: __t.u64(),
  channelName: __t.string(),
  agentId: __t.string(),
  subscribedAt: __t.u64(),
  lastReadId: __t.u64(),
});
export type Sub = __Infer<typeof Sub>;
