// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const SubmitReviewReducer = __t.object("SubmitReviewReducer", {
  stepId: __t.string(),
  reviewerId: __t.string(),
  verdict: __t.string(),
  rationale: __t.string(),
});
export type SubmitReviewReducer = __Infer<typeof SubmitReviewReducer>;
