// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  artifactPath: __t.string().primaryKey().name("artifact_path"),
  proposalId: __t.u64().name("proposal_id"),
  lastSdbHash: __t.string().name("last_sdb_hash"),
  lastGitCommit: __t.string().name("last_git_commit"),
  syncStatus: __t.string().name("sync_status"),
  lastSyncedAt: __t.u64().name("last_synced_at"),
  errorMessage: __t.option(__t.string()).name("error_message"),
});
