// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Test = __t.object("Test", {
  id: __t.u64(),
  testId: __t.string(),
  stepId: __t.string(),
  name: __t.string(),
  category: __t.string(),
  file: __t.string(),
});
export type Test = __Infer<typeof Test>;
