// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const TokenLedger = __t.object("TokenLedger", {
  id: __t.u64(),
  callId: __t.string(),
  agentId: __t.string(),
  modelName: __t.string(),
  inputTokens: __t.u64(),
  outputTokens: __t.u64(),
  cachedTokens: __t.u64(),
  totalUsd: __t.f64(),
  timestamp: __t.u64(),
});
export type TokenLedger = __Infer<typeof TokenLedger>;
