// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AgentMemory = __t.object("AgentMemory", {
  id: __t.u64(),
  agentIdentity: __t.string(),
  scopeProposalId: __t.u64(),
  key: __t.string(),
  val: __t.string(),
  updatedAt: __t.u64(),
});
export type AgentMemory = __Infer<typeof AgentMemory>;

export const AttachmentRegistry = __t.object("AttachmentRegistry", {
  id: __t.u64(),
  proposalId: __t.u64(),
  displayId: __t.string(),
  fileName: __t.string(),
  relativePath: __t.string(),
  fileType: __t.string(),
  contentHash: __t.string(),
  visionSummary: __t.option(__t.string()),
  timestamp: __t.u64(),
});
export type AttachmentRegistry = __Infer<typeof AttachmentRegistry>;

export const MessageLedger = __t.object("MessageLedger", {
  id: __t.u64(),
  channelName: __t.string(),
  senderIdentity: __t.string(),
  content: __t.string(),
  timestamp: __t.u64(),
});
export type MessageLedger = __Infer<typeof MessageLedger>;

export const Proposal = __t.object("Proposal", {
  id: __t.u64(),
  displayId: __t.string(),
  parentId: __t.option(__t.u64()),
  proposalType: __t.string(),
  category: __t.string(),
  domainId: __t.string(),
  title: __t.string(),
  status: __t.string(),
  priority: __t.string(),
  bodyMarkdown: __t.option(__t.string()),
  processLogic: __t.option(__t.string()),
  maturityLevel: __t.option(__t.u32()),
  repositoryPath: __t.option(__t.string()),
  budgetLimitUsd: __t.f64(),
  tags: __t.option(__t.string()),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type Proposal = __Infer<typeof Proposal>;

export const ProposalCriteria = __t.object("ProposalCriteria", {
  id: __t.u64(),
  proposalId: __t.u64(),
  description: __t.string(),
  isVerified: __t.bool(),
});
export type ProposalCriteria = __Infer<typeof ProposalCriteria>;

export const ProposalDecision = __t.object("ProposalDecision", {
  id: __t.u64(),
  proposalId: __t.u64(),
  title: __t.string(),
  decisionSummary: __t.string(),
  rationale: __t.string(),
  status: __t.string(),
  createdAt: __t.u64(),
});
export type ProposalDecision = __Infer<typeof ProposalDecision>;

export const ProposalVersion = __t.object("ProposalVersion", {
  id: __t.u64(),
  proposalId: __t.u64(),
  authorIdentity: __t.string(),
  versionNumber: __t.u32(),
  changeSummary: __t.string(),
  bodyDelta: __t.option(__t.string()),
  metadataDeltaJson: __t.string(),
  gitCommitSha: __t.option(__t.string()),
  timestamp: __t.u64(),
});
export type ProposalVersion = __Infer<typeof ProposalVersion>;

export const SecurityAcl = __t.object("SecurityAcl", {
  id: __t.u64(),
  agentIdentity: __t.string(),
  targetProposalId: __t.u64(),
  permissionId: __t.string(),
});
export type SecurityAcl = __Infer<typeof SecurityAcl>;

export const SecurityAuditLog = __t.object("SecurityAuditLog", {
  id: __t.u64(),
  actorIdentity: __t.string(),
  action: __t.string(),
  severity: __t.string(),
  timestamp: __t.u64(),
});
export type SecurityAuditLog = __Infer<typeof SecurityAuditLog>;

export const SpendingCaps = __t.object("SpendingCaps", {
  agentIdentity: __t.string(),
  dailyLimitUsd: __t.f64(),
  totalSpentTodayUsd: __t.f64(),
  isFrozen: __t.bool(),
});
export type SpendingCaps = __Infer<typeof SpendingCaps>;

export const SpendingLog = __t.object("SpendingLog", {
  id: __t.u64(),
  proposal_id: __t.u64(),
  agentIdentity: __t.string(),
  costUsd: __t.f64(),
  timestamp: __t.u64(),
});
export type SpendingLog = __Infer<typeof SpendingLog>;

export const SyncLedger = __t.object("SyncLedger", {
  artifactPath: __t.string(),
  proposalId: __t.u64(),
  lastSdbHash: __t.string(),
  lastGitCommit: __t.string(),
  syncStatus: __t.string(),
  lastSyncedAt: __t.u64(),
  errorMessage: __t.option(__t.string()),
});
export type SyncLedger = __Infer<typeof SyncLedger>;

export const WorkforcePulse = __t.object("WorkforcePulse", {
  identity: __t.string(),
  activeProposalId: __t.option(__t.u64()),
  lastSeenAt: __t.u64(),
  statusMessage: __t.string(),
  isZombie: __t.bool(),
});
export type WorkforcePulse = __Infer<typeof WorkforcePulse>;

export const WorkforceRegistry = __t.object("WorkforceRegistry", {
  identity: __t.string(),
  agentId: __t.string(),
  name: __t.string(),
  role: __t.string(),
  clearanceLevel: __t.u8(),
  squadId: __t.u32(),
  workspace: __t.string(),
  apiKey: __t.string(),
  isActive: __t.bool(),
});
export type WorkforceRegistry = __Infer<typeof WorkforceRegistry>;
