// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  proposalId: __t.u64(),
  title: __t.option(__t.string()),
  bodyMarkdown: __t.option(__t.string()),
  priority: __t.option(__t.string()),
  tags: __t.option(__t.string()),
  changeSummary: __t.string(),
};
