// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AddTeamMemberArgs = __t.object("AddTeamMemberArgs", {
  teamId: __t.string(),
  agentId: __t.string(),
  role: __t.string(),
});
export type AddTeamMemberArgs = __Infer<typeof AddTeamMemberArgs>;

export const CacheClearArgs = __t.object("CacheClearArgs", {
});
export type CacheClearArgs = __Infer<typeof CacheClearArgs>;

export const CacheSetArgs = __t.object("CacheSetArgs", {
  section: __t.string(),
  content: __t.string(),
});
export type CacheSetArgs = __Infer<typeof CacheSetArgs>;

export const ClaimStepArgs = __t.object("ClaimStepArgs", {
  stepId: __t.string(),
  agentId: __t.string(),
  expiresAt: __t.u64(),
});
export type ClaimStepArgs = __Infer<typeof ClaimStepArgs>;

export const CreateAcArgs = __t.object("CreateAcArgs", {
  acId: __t.string(),
  stepId: __t.string(),
  description: __t.string(),
});
export type CreateAcArgs = __Infer<typeof CreateAcArgs>;

export const CreateChannelArgs = __t.object("CreateChannelArgs", {
  name: __t.string(),
  description: __t.string(),
});
export type CreateChannelArgs = __Infer<typeof CreateChannelArgs>;

export const CreateCompArgs = __t.object("CreateCompArgs", {
  name: __t.string(),
  description: __t.string(),
});
export type CreateCompArgs = __Infer<typeof CreateCompArgs>;

export const CreateDiscussionArgs = __t.object("CreateDiscussionArgs", {
  stepId: __t.string(),
  agentId: __t.string(),
  content: __t.string(),
  noteType: __t.string(),
});
export type CreateDiscussionArgs = __Infer<typeof CreateDiscussionArgs>;

export const CreateGoalArgs = __t.object("CreateGoalArgs", {
  title: __t.string(),
  description: __t.string(),
});
export type CreateGoalArgs = __Infer<typeof CreateGoalArgs>;

export const CreateProposalArgs = __t.object("CreateProposalArgs", {
  title: __t.string(),
  description: __t.string(),
  proposedBy: __t.string(),
});
export type CreateProposalArgs = __Infer<typeof CreateProposalArgs>;

export const CreateStateNoteArgs = __t.object("CreateStateNoteArgs", {
  stepId: __t.string(),
  agentId: __t.string(),
  content: __t.string(),
  noteType: __t.string(),
});
export type CreateStateNoteArgs = __Infer<typeof CreateStateNoteArgs>;

export const CreateStepArgs = __t.object("CreateStepArgs", {
  displayId: __t.string(),
  title: __t.string(),
  body: __t.string(),
});
export type CreateStepArgs = __Infer<typeof CreateStepArgs>;

export const CreateTeamArgs = __t.object("CreateTeamArgs", {
  name: __t.string(),
  focus: __t.string(),
});
export type CreateTeamArgs = __Infer<typeof CreateTeamArgs>;

export const DeleteDiscussionArgs = __t.object("DeleteDiscussionArgs", {
  noteId: __t.u64(),
  agentId: __t.string(),
});
export type DeleteDiscussionArgs = __Infer<typeof DeleteDiscussionArgs>;

export const DeleteStateNoteArgs = __t.object("DeleteStateNoteArgs", {
  noteId: __t.u64(),
  agentId: __t.string(),
});
export type DeleteStateNoteArgs = __Infer<typeof DeleteStateNoteArgs>;

export const DeleteStepArgs = __t.object("DeleteStepArgs", {
  displayId: __t.string(),
});
export type DeleteStepArgs = __Infer<typeof DeleteStepArgs>;

export const EmitEventArgs = __t.object("EmitEventArgs", {
  actor: __t.string(),
  action: __t.string(),
  stateId: __t.option(__t.string()),
  payload: __t.string(),
});
export type EmitEventArgs = __Infer<typeof EmitEventArgs>;

export const GrantPrivilegeArgs = __t.object("GrantPrivilegeArgs", {
  agentId: __t.string(),
  permission: __t.string(),
  grantedBy: __t.string(),
});
export type GrantPrivilegeArgs = __Infer<typeof GrantPrivilegeArgs>;

export const MarkReadArgs = __t.object("MarkReadArgs", {
  channel: __t.string(),
  lastId: __t.u64(),
});
export type MarkReadArgs = __Infer<typeof MarkReadArgs>;

export const ProvisionSandboxArgs = __t.object("ProvisionSandboxArgs", {
  containerId: __t.string(),
  agentId: __t.string(),
  token: __t.string(),
  expiresAt: __t.u64(),
});
export type ProvisionSandboxArgs = __Infer<typeof ProvisionSandboxArgs>;

export const RecordTokensArgs = __t.object("RecordTokensArgs", {
  callId: __t.string(),
  agentId: __t.string(),
  modelName: __t.string(),
  inputTokens: __t.u64(),
  outputTokens: __t.u64(),
  cachedTokens: __t.u64(),
  totalUsd: __t.f64(),
});
export type RecordTokensArgs = __Infer<typeof RecordTokensArgs>;

export const RegisterAgentArgs = __t.object("RegisterAgentArgs", {
  id: __t.string(),
  agentType: __t.string(),
  name: __t.string(),
  reportsTo: __t.option(__t.string()),
});
export type RegisterAgentArgs = __Infer<typeof RegisterAgentArgs>;

export const ReleaseClaimArgs = __t.object("ReleaseClaimArgs", {
  stepId: __t.string(),
});
export type ReleaseClaimArgs = __Infer<typeof ReleaseClaimArgs>;

export const RemoveTeamMemberArgs = __t.object("RemoveTeamMemberArgs", {
  teamId: __t.string(),
  agentId: __t.string(),
});
export type RemoveTeamMemberArgs = __Infer<typeof RemoveTeamMemberArgs>;

export const RestoreStepArgs = __t.object("RestoreStepArgs", {
  displayId: __t.string(),
  parentId: __t.option(__t.u64()),
  depth: __t.u64(),
  compId: __t.option(__t.string()),
  teamId: __t.option(__t.string()),
  goalId: __t.option(__t.string()),
  title: __t.string(),
  status: __t.string(),
  body: __t.string(),
  description: __t.string(),
  acceptanceCriteria: __t.string(),
  implementationNotes: __t.string(),
  finalSummary: __t.string(),
  priority: __t.string(),
  labels: __t.string(),
  dependencies: __t.string(),
  assignee: __t.string(),
  claimedBy: __t.option(__t.string()),
  claimedAt: __t.option(__t.u64()),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type RestoreStepArgs = __Infer<typeof RestoreStepArgs>;

export const SendMessageArgs = __t.object("SendMessageArgs", {
  channel: __t.string(),
  content: __t.string(),
  msgType: __t.string(),
});
export type SendMessageArgs = __Infer<typeof SendMessageArgs>;

export const SetConfigArgs = __t.object("SetConfigArgs", {
  key: __t.string(),
  val: __t.string(),
});
export type SetConfigArgs = __Infer<typeof SetConfigArgs>;

export const SubmitReviewArgs = __t.object("SubmitReviewArgs", {
  stepId: __t.string(),
  reviewerId: __t.string(),
  verdict: __t.string(),
  rationale: __t.string(),
});
export type SubmitReviewArgs = __Infer<typeof SubmitReviewArgs>;

export const SubscribeChannelArgs = __t.object("SubscribeChannelArgs", {
  channel: __t.string(),
});
export type SubscribeChannelArgs = __Infer<typeof SubscribeChannelArgs>;

export const TransitionStepArgs = __t.object("TransitionStepArgs", {
  displayId: __t.string(),
  newStatus: __t.string(),
  AgentId: __t.string(),
  Reason: __t.option(__t.string()),
});
export type TransitionStepArgs = __Infer<typeof TransitionStepArgs>;

export const UpdateGoalStatusArgs = __t.object("UpdateGoalStatusArgs", {
  goalId: __t.u64(),
  newStatus: __t.string(),
});
export type UpdateGoalStatusArgs = __Infer<typeof UpdateGoalStatusArgs>;

export const VerifyAcArgs = __t.object("VerifyAcArgs", {
  acId: __t.string(),
});
export type VerifyAcArgs = __Infer<typeof VerifyAcArgs>;

