// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddCriteriaReducer from "../add_criteria_reducer";
import AuditLogReducer from "../audit_log_reducer";
import CheckCriteriaReducer from "../check_criteria_reducer";
import ClaimProposalReducer from "../claim_proposal_reducer";
import CreateProposalReducer from "../create_proposal_reducer";
import FreezeSpendingReducer from "../freeze_spending_reducer";
import GrantAclReducer from "../grant_acl_reducer";
import LogSpendingReducer from "../log_spending_reducer";
import MarkSyncErrorReducer from "../mark_sync_error_reducer";
import RecordDecisionReducer from "../record_decision_reducer";
import RecordSyncReducer from "../record_sync_reducer";
import RegisterAgentReducer from "../register_agent_reducer";
import RemoveCriteriaReducer from "../remove_criteria_reducer";
import RetireAgentReducer from "../retire_agent_reducer";
import RevokeAclReducer from "../revoke_acl_reducer";
import SendMessageReducer from "../send_message_reducer";
import SetMemoryReducer from "../set_memory_reducer";
import SetSpendingCapsReducer from "../set_spending_caps_reducer";
import TransitionProposalReducer from "../transition_proposal_reducer";
import UpdateProposalReducer from "../update_proposal_reducer";
import UpdatePulseReducer from "../update_pulse_reducer";
import WipeMemoryReducer from "../wipe_memory_reducer";

export type AddCriteriaParams = __Infer<typeof AddCriteriaReducer>;
export type AuditLogParams = __Infer<typeof AuditLogReducer>;
export type CheckCriteriaParams = __Infer<typeof CheckCriteriaReducer>;
export type ClaimProposalParams = __Infer<typeof ClaimProposalReducer>;
export type CreateProposalParams = __Infer<typeof CreateProposalReducer>;
export type FreezeSpendingParams = __Infer<typeof FreezeSpendingReducer>;
export type GrantAclParams = __Infer<typeof GrantAclReducer>;
export type LogSpendingParams = __Infer<typeof LogSpendingReducer>;
export type MarkSyncErrorParams = __Infer<typeof MarkSyncErrorReducer>;
export type RecordDecisionParams = __Infer<typeof RecordDecisionReducer>;
export type RecordSyncParams = __Infer<typeof RecordSyncReducer>;
export type RegisterAgentParams = __Infer<typeof RegisterAgentReducer>;
export type RemoveCriteriaParams = __Infer<typeof RemoveCriteriaReducer>;
export type RetireAgentParams = __Infer<typeof RetireAgentReducer>;
export type RevokeAclParams = __Infer<typeof RevokeAclReducer>;
export type SendMessageParams = __Infer<typeof SendMessageReducer>;
export type SetMemoryParams = __Infer<typeof SetMemoryReducer>;
export type SetSpendingCapsParams = __Infer<typeof SetSpendingCapsReducer>;
export type TransitionProposalParams = __Infer<typeof TransitionProposalReducer>;
export type UpdateProposalParams = __Infer<typeof UpdateProposalReducer>;
export type UpdatePulseParams = __Infer<typeof UpdatePulseReducer>;
export type WipeMemoryParams = __Infer<typeof WipeMemoryReducer>;

