export interface ProposalEditArgs {
	title?: string;
	description?: string;
	status?: string;
	priority?: "high" | "medium" | "low";
	directive?: string | null;
	domainId?: string;
	proposalType?: string;
	category?: string;
	labels?: string[];
	addLabels?: string[];
	removeLabels?: string[];
	assignee?: string[];
	ordinal?: number;
	dependencies?: string[];
	references?: string[];
	addReferences?: string[];
	removeReferences?: string[];
	documentation?: string[];
	addDocumentation?: string[];
	removeDocumentation?: string[];
	implementationPlan?: string;
	planSet?: string;
	planAppend?: string[];
	planClear?: boolean;
	implementationNotes?: string;
	notesSet?: string;
	notesAppend?: string[];
	notesClear?: boolean;
	auditNotes?: string;
	auditNotesSet?: string;
	auditNotesAppend?: string[];
	auditNotesClear?: boolean;
	finalSummary?: string;
	finalSummaryAppend?: string[];
	finalSummaryClear?: boolean;
	scopeSummary?: string;
	acceptanceCriteriaSet?: string[];
	acceptanceCriteriaAdd?: string[];
	acceptanceCriteriaRemove?: number[];
	acceptanceCriteriaCheck?: number[];
	acceptanceCriteriaUncheck?: number[];
	verificationProposalmentsSet?: string[];
	verificationProposalmentsAdd?: string[];
	verificationProposalmentsRemove?: number[];
	verificationProposalmentsCheck?: number[];
	verificationProposalmentsUncheck?: number[];
	requires?: string[];
	requiresAdd?: string[];
	requiresRemove?: number[];
	requiresClear?: boolean;
	maturity?: "new" | "active" | "mature" | "obsolete";
	builder?: string;
	auditor?: string;
	needs_capabilities?: string[];
	addNeedsCapabilities?: string[];
	removeNeedsCapabilities?: number[];
	external_injections?: string[];
	addExternalInjections?: string[];
	removeExternalInjections?: number[];
	unlocks?: string[];
	addUnlocks?: string[];
	removeUnlocks?: number[];
	proof?: string[];
	addProof?: string[];
	removeProof?: number[];
	rationale?: string;
}

export type ProposalEditRequest = ProposalEditArgs & { id: string };
