/**
 * in_app transport — leaves the envelope visible to the dashboard.
 *
 * Writes to a small `roadmap.notification_inbox` table that the dashboard polls
 * (or subscribes to via the existing WebSocket bridge). Each row is one alert
 * the operator should see in the UI without leaving the app.
 *
 * The table is created lazily on first dispatch so the transport works even
 * before the dedicated migration lands.
 */

import { query } from "../../../postgres/pool.ts";
import type {
	DispatchArgs,
	NotificationTransport,
} from "../types.ts";
import { TransportError } from "../types.ts";

let tableEnsured = false;

async function ensureTable(): Promise<void> {
	if (tableEnsured) return;
	await query(`
		CREATE TABLE IF NOT EXISTS roadmap.notification_inbox (
			id          bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
			queue_id    bigint REFERENCES roadmap.notification_queue(id) ON DELETE SET NULL,
			route_id    bigint,
			severity    text NOT NULL,
			kind        text NOT NULL,
			proposal_id bigint,
			title       text NOT NULL,
			body        text NOT NULL,
			payload     jsonb NOT NULL DEFAULT '{}'::jsonb,
			created_at  timestamptz NOT NULL DEFAULT now(),
			seen_at     timestamptz
		)
	`);
	tableEnsured = true;
}

export const inAppTransport: NotificationTransport = {
	name: "in_app",
	async send({ envelope, route }: DispatchArgs): Promise<void> {
		try {
			await ensureTable();
			await query(
				`INSERT INTO roadmap.notification_inbox
				 (queue_id, route_id, severity, kind, proposal_id, title, body, payload)
				 VALUES ($1, $2, $3, $4, $5, $6, $7, $8::jsonb)`,
				[
					envelope.queueId,
					route.id,
					envelope.severity,
					envelope.kind,
					envelope.proposalId,
					envelope.title,
					envelope.body,
					JSON.stringify(envelope.payload),
				],
			);
		} catch (err) {
			throw new TransportError("in_app", err);
		}
	},
};
