/**
 * STATE-45: MAP.md as Daemon Projection
 *
 * MAP.md is auto-generated by the daemon instead of manually updated.
 * All proposal transitions automatically reflect in the board view.
 *
 * AC#1: MAP.md generated from SQLite, not manually edited
 * AC#2: Board view reflects proposal changes within 30 seconds
 * AC#3: Conflicting manual edits rejected with clear error
 * AC#4: Historical MAP.md versions archived
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync, readdirSync, copyFileSync } from "node:fs";
import { join } from "node:path";
import { DatabaseSync } from "node:sqlite";

/** Configuration for MAP.md projection */
export interface MapProjectionConfig {
	/** Auto-generate MAP.md on proposal changes */
	autoGenerate: boolean;
	/** Maximum history versions to keep */
	maxHistoryVersions: number;
	/** Sections to include in MAP.md */
	sections: {
		summary: boolean;
		proposalTable: boolean;
		statistics: boolean;
		recentActivity: boolean;
	};
	/** File path for MAP.md */
	outputPath: string;
	/** Enable conflict detection */
	conflictDetection: boolean;
}

/** Proposal row from SQLite */
interface ProposalRow {
	id: string;
	title: string;
	status: string;
	assignee: string | null;
	priority: string | null;
	directive: string | null;
	labels: string | null;
	dependencies: string | null;
}

/** MAP.md generation result */
export interface MapGenerationResult {
	/** Whether generation succeeded */
	success: boolean;
	/** Path to generated file */
	path: string;
	/** Number of proposals included */
	proposalCount: number;
	/** Generation timestamp */
	generatedAt: string;
	/** Duration in ms */
	duration: number;
	/** Any warnings */
	warnings: string[];
}

/** Conflict detection result */
export interface ConflictCheck {
	/** Whether there's a conflict */
	hasConflict: boolean;
	/** Reason for conflict */
	reason?: string;
	/** Last known checksum */
	lastChecksum?: string;
	/** Current file checksum */
	currentChecksum?: string;
}

const DEFAULT_CONFIG: MapProjectionConfig = {
	autoGenerate: true,
	maxHistoryVersions: 10,
	sections: {
		summary: true,
		proposalTable: true,
		statistics: true,
		recentActivity: true,
	},
	outputPath: "roadmap/MAP.md",
	conflictDetection: true,
};

/** Grouped proposals by status for board view */
interface GroupedProposals {
	potential: ProposalRow[];
	active: ProposalRow[];
	review: ProposalRow[];
	complete: ProposalRow[];
	abandoned: ProposalRow[];
	[key: string]: ProposalRow[];
}

/**
 * MAP.md Projection - auto-generates MAP.md from SQLite proposal.
 */
export class MapProjection {
	private config: MapProjectionConfig;
	private dbPath: string;
	private checksumPath: string;
	private historyDir: string;
	private lastChecksum: string | null = null;
	private projectRoot: string;

	constructor(projectRoot: string, config?: Partial<MapProjectionConfig>) {
		this.projectRoot = projectRoot;
		this.config = { ...DEFAULT_CONFIG, ...config };
		this.dbPath = join(projectRoot, "roadmap", ".cache", "index.db");
		this.checksumPath = join(projectRoot, "roadmap", ".cache", "map-checksum.txt");
		this.historyDir = join(projectRoot, "roadmap", ".cache", "map-history");
		this.loadLastChecksum();
	}

	/**
	 * Load last known checksum for conflict detection.
	 */
	private loadLastChecksum(): void {
		if (existsSync(this.checksumPath)) {
			this.lastChecksum = readFileSync(this.checksumPath, "utf-8").trim();
		}
	}

	/**
	 * Save current checksum.
	 */
	private saveChecksum(checksum: string): void {
		const dir = join(this.projectRoot, "roadmap", ".cache");
		if (!existsSync(dir)) {
			mkdirSync(dir, { recursive: true });
		}
		writeFileSync(this.checksumPath, checksum);
		this.lastChecksum = checksum;
	}

	/**
	 * Simple checksum for content.
	 */
	private computeChecksum(content: string): string {
		let hash = 0;
		for (let i = 0; i < content.length; i++) {
			const char = content.charCodeAt(i);
			hash = ((hash << 5) - hash) + char;
			hash = hash & hash; // Convert to 32bit integer
		}
		return Math.abs(hash).toString(16);
	}

	/**
	 * AC#3: Check for conflicting manual edits.
	 */
	checkForConflicts(): ConflictCheck {
		const mapPath = join(this.projectRoot, this.config.outputPath);

		if (!existsSync(mapPath)) {
			return { hasConflict: false };
		}

		if (!this.lastChecksum) {
			return { hasConflict: false };
		}

		const content = readFileSync(mapPath, "utf-8");

		// Check for edit marker
		if (content.includes("<!-- MAP_EDITABLE -->")) {
			return {
				hasConflict: false, // User explicitly marked as editable
			};
		}

		// Check for auto-gen marker
		if (!content.includes("<!-- AUTO-GENERATED by roadmap daemon")) {
			return {
				hasConflict: true,
				reason: "MAP.md is missing the auto-generation marker. Manual edits may conflict with daemon projections.",
			};
		}

		const currentChecksum = this.computeChecksum(content);
		if (this.lastChecksum !== currentChecksum) {
			// File was modified since last generation
			// This could be a legitimate regeneration or a conflict
			// For now, we allow it but log it
			return {
				hasConflict: false,
				reason: "File was modified externally. Will be overwritten on next generation.",
				lastChecksum: this.lastChecksum,
				currentChecksum,
			};
		}

		return { hasConflict: false };
	}

	/**
	 * AC#1: Generate MAP.md from SQLite.
	 */
	generateMap(): MapGenerationResult {
		const startTime = Date.now();
		const warnings: string[] = [];
		const mapPath = join(this.projectRoot, this.config.outputPath);

		// Ensure output directory exists
		const dir = join(this.projectRoot, "roadmap");
		if (!existsSync(dir)) {
			mkdirSync(dir, { recursive: true });
		}

		// Read proposals from SQLite
		const proposals = this.readProposalsFromSQLite();

		if (proposals.length === 0) {
			warnings.push("No proposals found in database");
		}

		// Archive current version before overwriting
		if (existsSync(mapPath)) {
			this.archiveCurrentVersion();
		}

		// Generate content
		const content = this.buildMapContent(proposals);

		// Write MAP.md
		writeFileSync(mapPath, content);

		// Save checksum for conflict detection
		const checksum = this.computeChecksum(content);
		this.saveChecksum(checksum);

		return {
			success: true,
			path: mapPath,
			proposalCount: proposals.length,
			generatedAt: new Date().toISOString(),
			duration: Date.now() - startTime,
			warnings,
		};
	}

	/**
	 * Read proposals from SQLite database.
	 */
	private readProposalsFromSQLite(): ProposalRow[] {
		if (!existsSync(this.dbPath)) {
			return [];
		}

		try {
			const db = new DatabaseSync(this.dbPath);
			const rows = db.prepare(`
				SELECT id, title, status, assignee, priority, directive, labels, dependencies
				FROM proposals
				ORDER BY id
			`).all() as unknown as ProposalRow[];
			db.close();
			return rows;
		} catch {
			return [];
		}
	}

	/**
	 * Build MAP.md content from proposals.
	 */
	private buildMapContent(proposals: ProposalRow[]): string {
		const lines: string[] = [];
		const now = new Date().toISOString();

		// Header with auto-generation marker
		lines.push("<!-- AUTO-GENERATED by roadmap daemon - do not edit manually -->");
		lines.push("<!-- To make this file editable, add: <!-- MAP_EDITABLE --> -->");
		lines.push("");
		lines.push("# MAP.md — Project Roadmap");
		lines.push("");
		lines.push(`> Last updated: ${now}`);
		lines.push(`> Total proposals: ${proposals.length}`);
		lines.push("");

		// Group proposals by status
		const grouped = this.groupProposalsByStatus(proposals);

		// AC#2: Board view
		if (this.config.sections.proposalTable) {
			lines.push("## Board View");
			lines.push("");
			this.buildBoardView(lines, grouped);
			lines.push("");
		}

		// Statistics
		if (this.config.sections.statistics) {
			lines.push("## Statistics");
			lines.push("");
			this.buildStatistics(lines, grouped, proposals);
			lines.push("");
		}

		// Recent activity placeholder
		if (this.config.sections.recentActivity) {
			lines.push("## Recent Activity");
			lines.push("");
			lines.push("_Activity log updated by daemon_");
			lines.push("");
		}

		// Footer
		lines.push("---");
		lines.push("*Generated by roadmap daemon*");

		return lines.join("\n");
	}

	/**
	 * Group proposals by status for board view.
	 */
	private groupProposalsByStatus(proposals: ProposalRow[]): GroupedProposals {
		const grouped: GroupedProposals = {
			potential: [],
			active: [],
			review: [],
			complete: [],
			abandoned: [],
		};

		for (const proposal of proposals) {
			const status = (proposal.status || "").toLowerCase();
			if (status === "potential") grouped.potential.push(proposal);
			else if (status === "active") grouped.active.push(proposal);
			else if (status === "review") grouped.review.push(proposal);
			else if (status === "reached" || status === "complete") grouped.complete.push(proposal);
			else if (status === "abandoned") grouped.abandoned.push(proposal);
			else grouped.potential.push(proposal); // Default
		}

		return grouped;
	}

	/**
	 * Build board view section.
	 */
	private buildBoardView(lines: string[], grouped: GroupedProposals): void {
		// Table header
		lines.push("| New | Draft | Review | Active | Accepted | Complete |");
		lines.push("| --- | --- | --- | --- | --- | --- |");

		// Find max column length
		const maxRows = Math.max(
			grouped.potential.length, // Mapping potential to New for now
			(grouped as any).draft?.length || 0,
			grouped.review.length,
			grouped.active.length,
			(grouped as any).accepted?.length || 0,
			grouped.complete.length, // Mapping reached to Complete
		);

		for (let i = 0; i < maxRows; i++) {
			const cols = [
				this.formatProposalCell(grouped.potential[i]),
				this.formatProposalCell((grouped as any).draft?.[i]),
				this.formatProposalCell(grouped.review[i]),
				this.formatProposalCell(grouped.active[i]),
				this.formatProposalCell((grouped as any).accepted?.[i]),
				this.formatProposalCell(grouped.complete[i]),
			];
			lines.push(`| ${cols.join(" | ")} |`);
		}

		// Empty proposal
		if (maxRows === 0) {
			lines.push("| | | | | | |");
			lines.push("| *(empty)* | *(empty)* | *(empty)* | *(empty)* | *(empty)* | *(empty)* |");
		}
	}

	/**
	 * Format a proposal for table cell.
	 */
	private formatProposalCell(proposal?: ProposalRow): string {
		if (!proposal) return " ";

		let cell = `**${proposal.id}**`;
		if (proposal.assignee) {
			cell += ` @${proposal.assignee}`;
		}
		if (proposal.priority === "high") {
			cell += " 🔥";
		}
		return cell;
	}

	/**
	 * Build statistics section.
	 */
	private buildStatistics(lines: string[], grouped: GroupedProposals, proposals: ProposalRow[]): void {
		const stats = {
			new: grouped.potential.length,
			draft: (grouped as any).draft?.length || 0,
			active: grouped.active.length,
			review: grouped.review.length,
			accepted: (grouped as any).accepted?.length || 0,
			complete: grouped.complete.length,
			total: proposals.length,
		};

		const completionRate = stats.total > 0
			? Math.round((stats.complete / stats.total) * 100)
			: 0;

		lines.push(`- **Total proposals:** ${stats.total}`);
		lines.push(`- **Completion rate:** ${completionRate}%`);
		lines.push(`- **In progress:** ${stats.active + stats.review}`);
		lines.push(`- **New backlog:** ${stats.new}`);
		lines.push("");
		lines.push("| Status | Count |");
		lines.push("| --- | --- |");
		lines.push(`| New | ${stats.new} |`);
		lines.push(`| Draft | ${stats.draft} |`);
		lines.push(`| Review | ${stats.review} |`);
		lines.push(`| Active | ${stats.active} |`);
		lines.push(`| Accepted | ${stats.accepted} |`);
		lines.push(`| Complete | ${stats.complete} |`);
	}

	/**
	 * AC#4: Archive current MAP.md version.
	 */
	private archiveCurrentVersion(): void {
		const mapPath = join(this.projectRoot, this.config.outputPath);

		if (!existsSync(this.historyDir)) {
			mkdirSync(this.historyDir, { recursive: true });
		}

		// Create version filename with timestamp
		const timestamp = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
		const versionPath = join(this.historyDir, `MAP-${timestamp}.md`);

		copyFileSync(mapPath, versionPath);

		// Clean up old versions
		this.cleanupHistory();
	}

	/**
	 * Clean up old history versions.
	 */
	private cleanupHistory(): void {
		if (!existsSync(this.historyDir)) return;

		const files = readdirSync(this.historyDir)
			.filter((f) => f.startsWith("MAP-") && f.endsWith(".md"))
			.sort()
			.reverse();

		// Keep only maxHistoryVersions
		for (let i = this.config.maxHistoryVersions; i < files.length; i++) {
			const { unlinkSync } = require("node:fs");
			unlinkSync(join(this.historyDir, files[i]));
		}
	}

	/**
	 * Get archived versions.
	 */
	getArchivedVersions(): string[] {
		if (!existsSync(this.historyDir)) return [];

		return readdirSync(this.historyDir)
			.filter((f) => f.startsWith("MAP-") && f.endsWith(".md"))
			.sort()
			.reverse();
	}

	/**
	 * Get content of an archived version.
	 */
	getArchivedVersion(filename: string): string | null {
		const path = join(this.historyDir, filename);
		if (!existsSync(path)) return null;
		return readFileSync(path, "utf-8");
	}

	/**
	 * Update configuration.
	 */
	updateConfig(config: Partial<MapProjectionConfig>): MapProjectionConfig {
		this.config = { ...this.config, ...config };
		return this.config;
	}

	/**
	 * Get current configuration.
	 */
	getConfig(): MapProjectionConfig {
		return { ...this.config };
	}

	/**
	 * Force regeneration (ignores conflict check).
	 */
	forceRegenerate(): MapGenerationResult {
		return this.generateMap();
	}
}

/**
 * Create a MAP.md projection for a project.
 */
export function createMapProjection(
	projectRoot: string,
	config?: Partial<MapProjectionConfig>,
): MapProjection {
	return new MapProjection(projectRoot, config);
}
